export const TOGGLE_DARKMODE = "TOGGLE_DARKMODE"

export const FETCH_CATEGORIES_DATA_SUCCESS = "FETCH_CATEGORIES_DATA_SUCCESS"
export const FETCH_CATEGORIES_DATA_FAILURE = "FETCH_CATEGORIES_DATA_FAILURE"
